language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t basov/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true basov/docker-frontend npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "eu-central-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-eu-central-1-160682765790"
  bucket_path: "docker-frontend"
  on:
    branch: master
